name: ESP32 Filesystem Build

on:
  push:
    branches:
      - main
      - feat/actions-build
  pull_request:
    branches:
      - main

jobs:
  build_filesystem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t esp32-builder -f Dockerfile .

      - name: Run container and generate fs.bin
        run: |
          docker run --name esp32-fs-builder esp32-builder /bin/bash
          docker cp esp32-fs-builder:/fs.bin .

      - name: Validate generated filesystem
        run: |
          test -f fs.bin
          test -s fs.bin
          echo "Teste"

      - name: Validate project files
        run: |
          test -f src/main.py
          test -f diagram.json
          test -f wokwi.toml
          test -f flasher_args.json
          echo "Project files validated successfully"
